const router = require('express').Router();
const c = require('../controllers/auth.controller');
router.post('/register', c.register);
router.post('/verify-email', c.verifyEmail);
router.post('/resend-code', c.resendCode);
router.post('/login', c.login);
router.post('/refresh', c.refresh);
const { verifyJWT } = require('../middlewares/auth.middleware');
router.post('/logout', verifyJWT, c.logout);
module.exports = router;
